version: '3.8'

services:
  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_CONTENT_DIR: ${BASE_CONTENT_DIR}
        NODE_ENV: ${NODE_ENV}
        NEXT_PUBLIC_GTM_ID: ${NEXT_PUBLIC_GTM_ID}
        NEXT_PUBLIC_GA_ID: ${NEXT_PUBLIC_GA_ID}
        # NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        # NEXT_PUBLIC_SITE_NAME: ${NEXT_PUBLIC_SITE_NAME}
        # NEXT_PUBLIC_SITE_DESCRIPTION: ${NEXT_PUBLIC_SITE_DESCRIPTION}
        # NEXT_PUBLIC_SITE_KEYWORDS: ${NEXT_PUBLIC_SITE_KEYWORDS}
        # NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_TRACKING_ID}
    container_name: next-front-page
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      # - ./public:/app/public
      # - ./posts:/app/posts
      - /var/www/eurekatop/public:/app/public
      - /var/www/eurekatop/posts:/app/posts
    #restart: unless-stopped
