version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
#      platform: linux/arm64
    container_name: next-front-page
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
